#!/bin/bash
# codeTester
# Author: Steven George
# Purpose: Test strmath.c

for file in test*; do
    ./strmath < "$file" > myOut 2> myErr

    echo $? >> myOut

    ./exStrmath < "$file" > exOut 2> exErr

    echo $? >> exOut

    echo "Test File $file"

    echo "stdout diffs:"
    diff myOut exOut

    echo "stderr diffs:"
    diff exErr exOut

done